### ISSUE TITLE
bucket of cow milk doesn't cure Pillager curse

### ISSUE THREAD

**Issue by AngleWyrm10** [cech12/BucketLib#12]
Pillager curse remains active after drinking a ceramic bucket of cow milk.

**Comment by cech12** [comment]
Thanks for your report! Which version are you using?

**Comment by cech12** [comment]
I found the issue in the BucketLib mod. So, I think you are playing in version 1.18.

**Comment by cech12** [comment]
Fixed and will be released in 1.18.2-0.5.3.3
