### ISSUE TITLE
[Bug]: BucketLib is putting an empty NBT tag on items that are in the first slot of the crafting table

### ISSUE THREAD

**Issue by Peca21** [cech12/BucketLib#13]
### Minecraft Version

1.18.2

### Forge Version

40.1.25

### Mod Version

bucketlib-1.18.2-0.5.3.3

### Modpack or other Mod

No other mods, only this one installed

### Describe the Issue

Placing items in the crafting table then taking them out will result in one of them being unstackable because an empty NBT tag is being applied to it for no reason.
Here is the video of the issue: https://streamable.com/m3z592
NBTExplorer screenshot:
![NBTExplorer screenshot](https://user-images.githubusercontent.com/13818400/170588830-05ff5147-62f4-4548-bc93-a275ccd85028.png)

### Logs

https://paste.ee/p/fLKrk

### Do you use any performance-enhancing mods (e.g. OptiFine)?

No

**Comment by cech12** [comment]
Thanks for your detailed report! The connected commit fixed the issue and it will be released soon in 1.18.2-0.5.3.4.
