### ISSUE TITLE
[Bug]: Incompatibility with ex nihilo sequentia unable to insert liquids in barrel

### ISSUE THREAD

**Issue by TimeheroTH** [cech12/BucketLib#15]
### Minecraft Version

1.18.2

### Forge Version

40.1.23

### Mod Version

1.0.2.1

### Modpack or other Mod

unable to place liquids in barrel of ex nihilo sequentia mod version: ExNihiloSequentia-1.18.2-20220530-183458.jar

### Describe the Issue

when i pick up a liquid from an exnihilo barrel the liquids could be taken correctly but when i want to put a liquid from the wooden bucket to the exnihilo barrel doesn't work; the liquid stay stucked in the bucket and don't fill the barrel

**Comment by cech12** [comment]
Thanks for your report! When I have time, I will look into this :)

**Comment by TimeheroTH** [comment]
Thank you i hope you could do as soon as you can because i have tried ceramic buckets and i have the same issue ;)

**Comment by cech12** [comment]
Yes, it should be an compatibility issue between BucketLib and Ex Nihilo. Maybe on Ex Nihilo side. ^^ But I will look into it in some days :)

https://github.com/NovaMachina/ExNihiloSequentia/blob/1.18/src/main/java/novamachina/exnihilosequentia/common/blockentity/barrel/mode/FluidsBarrelMode.java#L201
BucketLib buckets are not a BucketItem. To be more compatible, ExNihilo needs a change here.

**Comment by TimeheroTH** [comment]
Hi i have to send a pm to the exnihilo creator to modify this line to resolve the incompatibility? thank you for your precious time ^^
ps. Is there a way to resolve this issue by myself? How could that string been modified?

**Comment by cech12** [comment]
Hey, you could open an issue for Ex Nihilo or send a pm to the creator if you want. But when I have time, I would open a PR for Ex Nihilo to fix that issue. :)

If you know how to fix this issue, you can also make this PR, but I don't know how much programming knowledge you have^^

**Comment by cech12** [comment]
connected issue: https://github.com/NovaMachina-Mods/ExNihiloSequentia/issues/323

**Comment by cech12** [comment]
@TimeheroTH 
I opened a PR for Ex Nihilo Sequentia to fix that issue. I hope it will be merged and released for 1.18, because the 1.19 update is already in development for this mod.

**Comment by cech12** [comment]
@TimeheroTH The PR was merged and a new version of Ex Nihilo Sequentia was released. (ExNihiloSequentia-1.18.2-20220620-173540) 

I hope, this fixes the issue. :)

**Comment by cech12** [comment]
I tested ExNihiloSequentia-1.18.2-20220620-173540 with bucketlib-1.18.2-0.5.3.4 and filling barrels is possible now. 

@TimeheroTH If you find other compatibility issues, please let me know. :)

**Comment by TimeheroTH** [comment]
Thank you so much! Another compatibility issue is to waterlog the sieve,wooden water bucket couldn't waterlog a sieve

**Comment by cech12** [comment]
@TimeheroTH Sieves of Ex Nihilo cannot be waterlogged by vanilla buckets as well. So, that is not an issue of my mod ;)
