### ISSUE TITLE
[Bug]: Unable to insert milk into exnihilo sequentia barrel

### ISSUE THREAD

**Issue by TimeheroTH** [cech12/BucketLib#22]
### Minecraft Version

1.18.2

### Forge Version

40.1.68

### Mod Version

0.5.3.7

### Modpack or other Mod

incompatibility with bucket lib 0.5.3.7 ed exnihilosequentia 20220818.010806; unable to put milk with a wooden or ceramic bucket into a barrel of exnihilo.
I sent this message to exnihilo owner to resolve this issue. Thank you

### Describe the Issue

If you right click with a milk wooden or ceramic bucket the empy barrel doesn't fill up;
while doing this if  i have a milk wooden or ceramic bucket and the barrel is full of another liquid, the bucket take this liquid and empty the barrel and when i right click the empty barrel the second fluid go into the barrel while milk is always in the bucket.

**Comment by cech12** [comment]
Thanks for your report. I will look into that.

Related issue: https://github.com/NovaMachina-Mods/ExNihiloSequentia/issues/347

**Comment by cech12** [comment]
@TimeheroTH is there any possibility to put milk into a barrel in Ex Nihilo Sequentia? For example with a vanilla milk bucket?
I cannot find such behaviour.

**Comment by cech12** [comment]
I fixed the strange behaviour that milk buckets could be filled with other fluids in 1.18.2-0.5.3.8 and 1.19-1.0.3.1.
Filling a Ex Nihilo barrel with milk is no feature of Ex Nihilo, so this is not a compatibility issue.

**Comment by cech12** [comment]
I reopened the issue, because there was missing information that another mod enabeled the Forge milk fluid and only in this case milk can be placed into barrels with a vanilla bucket. The BucketLib buckets do not work in this case and this should be fixed here. :)

**Comment by remplerus** [comment]
to be clear: forge itself adds that possibility :D

**Comment by TimeheroTH** [comment]
Important is that now with all the information we arrived to a solution. Thank you both for the patience :D

**Comment by cech12** [comment]
I fixed the fluid handler of the milk bucket when the milk fluid of Forge is enabled. The versions 1.18.2-0.5.3.9 and 1.19-1.0.3.2 contain the changes. Thanks for your report. :)
