### ISSUE TITLE
[Bug]: The bucket for Naturalist Snail does not have a texture

### ISSUE THREAD

**Issue by ZAPGam1ng** [cech12/BucketLib#24]
### Minecraft Version

1.18.2

### Forge Version

40.2.0

### Mod Version

0.5.3.9

### Modpack or other Mod

The bug is Related to the [Naturalist](https://www.curseforge.com/minecraft/mc-mods/naturalist) mod

### Describe the Issue

The Bucket Of Snail does not have a texture

**Comment by cech12** [comment]
Thanks for your report. There is already a PR which fixes this issue: https://github.com/starfish-studios/Naturalist/pull/9
If you need it before this PR is merged, you can make a small resource pack with the changes listed here: https://github.com/starfish-studios/Naturalist/pull/9/files

**Comment by cech12** [comment]
Fixed by adding the Snail-texture of Naturalist to this mod. Maybe Naturalist will add it by themselves in the future. :)
