### ISSUE TITLE
[Bug]: Supposed 1.20-1-2.2.0.0 version claims to be 1.20.1-2.1.0.0 in the mod list

### ISSUE THREAD

**Issue by Sinhika** [cech12/BucketLib#27]
### Minecraft Version

1.20.1

### Forge Version

1.20.1-47.1.0

### Mod Version

Not sure

### Modpack or other Mod

Again, testing in conjunction with SimpleOres, SimpleCoreLib, and Ashenwheat mods.

### Describe the Issue

Gradle is supposedly pulling the 2.2.0.0 version of BucketLib, yet it shows up in the mod list as 2.1.0.0. A quick look at your source code shows that gradle.properties still lists the bucketLib version as 2.1.0.0.

### Do you use any performance-enhancing mods (e.g. OptiFine)?

No.

**Comment by cech12** [comment]
Thanks for your report. This will be fixed in the upcoming version 1.20.1-2.2.0.1
