### ISSUE TITLE
[Bug]: Creative mode milking spawns extra vanilla bucket

### ISSUE THREAD

**Issue by Sinhika** [cech12/BucketLib#28]
### Minecraft Version

1.20.1

### Forge Version

1.20.1-47.1.0

### Mod Version

ostensibly 2.2.0.0

### Modpack or other Mod

As usual, testing with SimpleCoreLib, SimpleOres, and Ashenwheat.

### Describe the Issue

In addition to the usual weird creative mode behavior met in vanilla minecraft, milking a cow in creative mode when you only have one empty BucketLib bucket on your bar causes not only a full Bucketlib milk bucket to spawn (expected), but an additional full vanilla milk bucket (not expected).

For comparison, picking up water in creative mode with an empty bucketLib bucket only spawns the full creative mode bucketLib bucket, in addition to the empty bucketLib bucket, which is expected behavior. No vanilla buckets appear.

**Comment by cech12** [comment]
Thanks for reporting! 

This is an known bug, that I don't know to fix and react dynamically on different milkable entities xD There is a TODO here: https://github.com/cech12/BucketLib/blob/1.20/src/main/java/cech12/bucketlib/util/WorldInteractionUtil.java#L36

Maybe sometimes I will find a fix, but it has a very low priority for me.

**Comment by cech12** [comment]
Fixed and released in 1.20.1-2.2.0.2
