### ISSUE TITLE
[Bug]: Crash when used with rubidium

### ISSUE THREAD

**Issue by soupbowle** [cech12/BucketLib#30]
### Minecraft Version

1.20.1

### Forge Version

47.1.0, 47.1.44

### Mod Version

2.3.0.0

### Modpack or other Mod

Simpleores2 - 6.0.0.3 - https://www.curseforge.com/minecraft/mc-mods/simpleores
SimpleCore API - 6.0.1.2 - https://www.curseforge.com/minecraft/mc-mods/simplecore-api
JEI - 15.2.0.23 - https://www.curseforge.com/minecraft/mc-mods/jei
Rubidium - 0.7.0a - https://www.curseforge.com/minecraft/mc-mods/rubidium

### Describe the Issue

I was trying to play with the rubidium mod and it crashes when I render a copper lava cube from the simpleOres mod. You can see it just typing lava in the creative tab.

### Logs

log: https://pastebin.com/UE2XSm91 

### Do you use any performance-enhancing mods (e.g. OptiFine)?

Rubidium

### Related issue

https://github.com/Sinhika/SimpleOres2/issues/66

**Comment by soupbowle** [comment]
Also this is the crash log in case it is useful: https://pastebin.com/D4cNu5YM

**Comment by cech12** [comment]
Thanks for your report.
it looks like this issue: https://github.com/Asek3/Rubidium/issues/577

https://github.com/Asek3/rubidium-upstream/pull/2

**Comment by cech12** [comment]
As a workaround: Don't use Rubidium :)

**Comment by cech12** [comment]
Fixed in Rubidium 0.7.1
