### ISSUE TITLE
[Question]: Bucket Clipping

### ISSUE THREAD

**Issue by crispytwig** [cech12/BucketLib#33]
### Minecraft Version

1.20.1

### Forge Version

47.2.0

### Mod Version

N/A

### Modpack or other Mod

Naturalist

### Describe the Issue

We've been using your bucket models and such for a while, but I recently changed the overlay texture of the Snail Bucket and it is now having clipping issues. Have you run into this, and how can we fix it?

Kind regards,

**Comment by cech12** [comment]
@crispytwig Yes, I have run into clipping issues with other mods. It should be a Forge issue at the "forge:item/default" model, because the vanilla item model does not have the clipping issues, as fas as I know. Maybe changing the parent to "item/generated" could fix the issue for your model?!

**Comment by cech12** [comment]
I saw, that your model already using the vanilla model as parent. Then maybe there is a Vanilla bug?! Another workaround could be, to cut out the clipping pixels from the lower_bucket texture, but you are using the lower bucket also for other textures...

**Comment by cech12** [comment]
It seems to be a Vanilla Minecraft issue that is not resolved yet:
- https://bugs.mojang.com/browse/MC-259368
- https://bugs.mojang.com/browse/MC-167526
- https://bugs.mojang.com/browse/MC-73186

**Comment by crispytwig** [comment]
> I saw, that your model already using the vanilla model as parent. Then maybe there is a Vanilla bug?! Another workaround could be, to cut out the clipping pixels from the lower_bucket texture, but you are using the lower bucket also for other textures...

If I make a custom texture specifically for our Snail Bucket and don't edit the positions/textures of the overlay, would it still be good for your mod?

**Comment by cech12** [comment]
Important for my mod is, that there is a texture of the bucket content and it is seperated from the texture of the bucket. (See here: https://github.com/cech12/BucketLib/wiki/Developer-Guide#textures)

I saw that you are adding multiple colors to your snail and the textures. This is not supported by my mod yet^^ Maybe I find a dynamic way to support such buckets by reading the original model files, but for now I would need one snail texture `assets/YOURMOD/textures/item/bucket_content/snail.png` which is used for every snail.

**Comment by crispytwig** [comment]
> Important for my mod is, that there is a texture of the bucket content and it is seperated from the texture of the bucket. (See here: https://github.com/cech12/BucketLib/wiki/Developer-Guide#textures)
> 
> I saw that you are adding multiple colors to your snail and the textures. This is not supported by my mod yet^^ Maybe I find a dynamic way to support such buckets by reading the original model files, but for now I would need one snail texture `assets/YOURMOD/textures/item/bucket_content/snail.png` which is used for every snail.

So as long as the snail textures are there and normal, the bucket texture does not matter and I can edit it how I please, yes?

**Comment by cech12** [comment]
Yes, the bucket texture is not used by my mod. Only the content texture :)

**Comment by cech12** [comment]
Using this mod could also fix the z-fighting issue: https://www.curseforge.com/minecraft/mc-mods/model-gap-fix

**Comment by crispytwig** [comment]
> Yes, the bucket texture is not used by my mod. Only the content texture :)

Thanks! I'll just make my own bucket texture for the Snail Bucket then. Have a good one!
