### ISSUE TITLE
[Bug]: 1.20.4 - Fabric max stack size is defaulting to 1

### ISSUE THREAD

**Issue by Janbsh** [cech12/BucketLib#40]
### Minecraft Version

1.20.4

### Mod Loader

Quilt

### Mod Loader Version

0.26.1-beta.1

### Mod Version

1.20.4-3.2.1.0

### Describe the Issue

The max stack size is defaulting to 1, I saw that this was a known issue but I'm pretty sure I know why its happening so I wanted to mention it just in case I am right.
![image](https://github.com/cech12/BucketLib/assets/104053630/f4c7cffe-22e4-4776-b11a-b9173c0e7c87)
I'm pretty sure you are setting the max count to 1.

**Comment by cech12** [comment]
Yes, that is right. I am setting it to one, because if I am setting it to a larger value, filled buckets are also be stackable to that value and in Fabric/Quilt 1.20.4 there is no stack sensitive functionality for this behaviour.

It is fixed since 1.20.6
