### ISSUE TITLE
[Bug]: Disappearing Buckets

### ISSUE THREAD

**Issue by CJDevZ** [cech12/BucketLib#42]
### Minecraft Version

1.21

### Mod Loader

Fabric

### Mod Loader Version

0.15.11

### Mod Version

4.0.0.4

### Modpack or other Mod

The bug is related to Wooden Bucket.

### Describe the Issue

It's pretty easy to replicate. You just need to take water out of a cauldron. The bucket will disappear.

### Logs

https://pastebin.com/j4v3hHYH

**Comment by cech12** [comment]
Thanks for your report :) I will look into that :)

**Comment by cech12** [comment]
Fixed in upcoming release 1.21-4.0.0.5
Thanks again for your report! :)
