### ISSUE TITLE
[Bug]: User reports BucketLib buckets do not stack after holding fish or axolotls

### ISSUE THREAD

**Issue by Sinhika** [cech12/BucketLib#46]
### Minecraft Version

1.20.1

### Mod Loader

Forge

### Mod Loader Version

Unreported

### Mod Version

Unreported

### Modpack or other Mod

SimpleOres 2 copper buckets. See https://github.com/Sinhika/SimpleOres2/issues/68.

### Describe the Issue

Per user report in above bug report:

> ### Issue
> 
> Copper buckets that have been used on fish or axolotls don't clean up their NBT and thus can't stack with unused buckets.
> This causes issues with storage tech and other systems without fuzzy NBT checking.
> 
> ### How to reproduce
> 
>     Pick up an Axolotl for example
>     Release the creature
>     Notice the bucket has 3 NBT tags thus causing the issue
>

**Comment by cech12** [comment]
Thanks for the report! I will look into that, when I have time.

**Comment by cech12** [comment]
Hey @Sinhika,

thanks again for the report. The issue was already fixed in 1.20.6 and later. The upcoming versions 1.20.1-2.3.4.3 and 1.20.4-3.2.1.5 are fixing it for Minecraft 1.20.1 and 1.20.4.
