### ISSUE TITLE
[Feature]: Config for deciding if buckets should flip 180°

### ISSUE THREAD

**Issue by Konhaiii** [cech12/BucketLib#50]
### Describe the Feature

Right now, buckets simply check if the fluid density is lower than air to determine if it should rotate 180° or not.
I think a cool feature would be having a config file where we can blacklist fluid namespaces ("modid:fluid_name") from the previous behavior.

Maybe even just a tag, if a fluid is in the tag "bucketlib:non_gaseous", its bucket never gets rotated.

**Comment by cech12** [comment]
@Konhaiii Thanks for your idea! I will think about that. The fluid tag sounds good to me. :) Which Minecraft version are you using?

**Comment by Konhaiii** [comment]
@cech12 Thank you for your reply, I'm currently using 1.20.1

**Comment by cech12** [comment]
@Konhaiii Since it's a small adjustment, I would add the feature to all versions from 1.20.1. :) Do you have an example mod with a flipped liquid?

**Comment by Konhaiii** [comment]
@cech12 Thank you ! I was recently playing with Chemlib, which adds a lot of different liquids, and a lot of them are flipped.

**Comment by cech12** [comment]
The feature was added in the upcoming versions: 

- 1.20.1-2.3.5.0
- 1.20.4-3.2.2.0
- 1.20.6-3.3.1.0
- 1.21-4.1.1.0

Thanks again for the idea! :)

**Comment by Konhaiii** [comment]
Thank you for your responsiveness ! :)
